version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/ruby:2.5-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
    steps:
      - checkout

      - type: cache-restore
        name: Sys Conf CPUs Restore
        key: libsysconfcpus

      - run:
          name: Sys Conf CPUs Install
          command: |
            git clone https://github.com/obmarg/libsysconfcpus.git
            cd libsysconfcpus
            ./configure
            make
            sudo make install

      - type: cache-save
        name: Sys Conf CPUs Store
        key: libsysconfcpus
        paths:
          - ~/libsysconfcpus

      - type: cache-restore
        name: Bundler Cache Restore
        key: bundle-{{ checksum "Gemfile" }}

      - run:
          name: Bundler Install
          command: |
            gem update --system
            bundle check || bundle install

      - type: cache-save
        name: Bundler Cache Store
        key: bundle-{{ checksum "Gemfile" }}
        paths:
          - vendor/bundle

      - type: cache-restore
        name: Yarn Cache Restore
        key: yarn-{{ checksum "yarn.lock" }}

      - run:
          name: Yarn Install
          command: |
            yarn install --cache-folder ~/.cache/yarn
            yarn add elm --dev

      - type: cache-save
        name: Yarn Cache Store
        key: yarn-{{ checksum "yarn.lock" }}
        paths:
          - ~/.cache/yarn

      - run:
          name: Code Quality Run
          command: bundle exec rake

      - run:
          name: Test Run
          command: |
            (
              cd ~/project/tests
              ../node_modules/.bin/elm-package install --yes
            )
            yarn ci
