version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/ruby:node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
    steps:
      - checkout

      - run:
          name: Environment Setup
          command: |
            printf "%s\n" 'export CI_RUBY_VERSION=$(cat ".ruby-version" | tr -d "\n")' >> $BASH_ENV

      - type: cache-restore
        name: Sys Conf CPUs Restore
        key: libsysconfcpus

      - run:
          name: Sys Conf CPUs Install
          command: |
            git clone https://github.com/obmarg/libsysconfcpus.git
            cd libsysconfcpus
            ./configure
            make
            sudo make install

      - type: cache-save
        name: Sys Conf CPUs Store
        key: libsysconfcpus
        paths:
          - ~/libsysconfcpus

      - type: cache-restore
        name: Ruby Restore
        key: ruby-{{checksum ".ruby-version"}}

      - run:
          name: Ruby Install
          command: |
            curl https://cache.ruby-lang.org/pub/ruby/${CI_RUBY_VERSION::-2}/ruby-$CI_RUBY_VERSION.tar.bz2 > ../ruby-$CI_RUBY_VERSION.tar.gz
            cd ..
            tar --extract --bzip2 --verbose --file ruby-$CI_RUBY_VERSION.tar.gz
            cd ruby-$CI_RUBY_VERSION
            ./configure
            make
            make update-gems
            make extract-gems
            sudo make install

      - type: cache-save
        name: Ruby Store
        key: ruby-{{checksum ".ruby-version"}}
        paths:
          - ../ruby-$CI_RUBY_VERSION

      - type: cache-restore
        name: Bundler Restore
        key: bundler-{{checksum "Gemfile"}}

      - run:
          name: Bundler Install
          command: |
            gem update --system
            bundle install --path vendor/bundle

      - type: cache-save
        name: Bundler Store
        key: bundler-{{checksum "Gemfile"}}
        paths:
          - vendor/bundle

      - type: cache-restore
        name: Yarn Cache Restore
        key: yarn-{{ checksum "yarn.lock" }}

      - run:
          name: Yarn Install
          command: |
            yarn install --cache-folder ~/.cache/yarn
            yarn add elm --dev

      - type: cache-save
        name: Yarn Cache Store
        key: yarn-{{ checksum "yarn.lock" }}
        paths:
          - ~/.cache/yarn

      - run:
          name: Code Quality Run
          command: bundle exec rake

      - run:
          name: Test Run
          command: |
            (
              cd ~/project/tests
              ../node_modules/.bin/elm-package install --yes
            )
            yarn ci
